import cuid from 'cuid';

const defaultPopupTemplateStyles = {
  'popup-outer-circle': {
    uniqueKey: cuid(),
    slot: { textContent: '' },
    attribute: { placeholder: '', classList: ['popup-block', 'fadeInDown'] },
    styles: {
      position: 'absolute !important',
      left: '50% !important',
      top: '50% !important',
      transform: 'translate(-50%, -50%) !important',
      color: 'rgb(0, 0, 0) !important',
      borderRadius: '200px !important',
      height: '400px !important',
      width: '400px !important',
      backgroundColor: 'rgb(255, 255, 255) !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '4px !important',
      borderStyle: 'solid !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-inner-circle': {
    slot: { textContent: '' },
    attribute: { placeholder: '' },
    styles: {
      color: 'rgb(0, 0, 0) !important',
      position: 'unset !important',
      borderRadius: '190px !important',
      height: '380px !important',
      width: '380px !important',
      backgroundColor: 'rgb(223, 122, 94) !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderStyle: 'solid !important',
      transform: 'translate(6.59998px, 6.60001px) !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-1': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderstyle: 'solid !important',
      transform: 'translate(119px, 18px) !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-2': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderstyle: 'solid !important',
      transform: 'translate(227px, 13px) !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-3': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderstyle: 'solid !important',
      transform: 'translate(174px, 0px) !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-text-1': {
    slot: { textContent: 'Get a Discount for shopping <br />with us' },
    attribute: { placeholder: '' },
    styles: {
      color: '#ffffff !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderstyle: 'solid !important',
      transform: 'translate(54.0999px, 80.8px) !important',
      textAlign: 'center !important',
      fontSize: '23px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-text-2': {
    slot: { textContent: 'Get a Discount for shopping with us' },
    attribute: { placeholder: '' },
    styles: {
      color: '#ffffff !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px !important',
      borderstyle: 'solid !important',
      transform: 'translate(73.0999px, 174.8px) !important',
      textAlign: 'center !important',
      fontSize: '15px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-input-1': {
    slot: { textContent: '' },
    attribute: { placeholder: 'Enter Your Text Here' },
    styles: {
      transform: 'translate(77.0147px, 167.846px) !important',
      borderRadius: '2px !important',
      height: '50.5px !important',
      width: '250px !important',
      lineHeight: '1.5 !important',
      fontSize: '18px !important',
      fontFamily: 'Poppins !important',
      background: 'white !important',
      paddingRight: '10px !important',
      paddingLeft: '10px !important',
      direction: 'rtl !important',
      borderStyle: 'none !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-button': {
    slot: { textContent: 'Lets Go ljsoiuoisg' },
    attribute: { placeholder: '' },
    styles: {
      transform: 'translate(46.0412px, 173.587px) !important',
      borderRadius: '2px !important',
      lineHeight: '1.5 !important',
      fontSize: '18px !important',
      color: '#ffffff !important',
      fontFamily: 'Poppins !important',
      background: '#000000 !important',
      paddingRight: '10px !important',
      paddingLeft: '10px !important',
      direction: 'ltr !important',
      width: '300px !important',
      height: '50.5px !important',
      backgroundColor: '#000000 !important',
      borderStyle: 'none !important',
      boxSizing: 'border-box !important',
    },
  },
};

export const editables = {
  text: ['textContent', 'color', 'fontSize'],
  outerCirlce: ['backgroundColor', 'borderColor', 'animationClass'],
  circle: ['backgroundColor', 'borderColor'],
  input: ['placeholder', 'direction'],
  button: ['backgroundColor', 'textContent', 'color'],
};

export default defaultPopupTemplateStyles as Record<string, Record<string, unknown>>;
