import cuid from 'cuid';

const defaultPopupTemplateStyles = {
  'popup-outer-circle': {
    uniqueKey: cuid(),
    slot: { textContent: '' },
    attribute: { placeholder: '', classList: ['popup-block', 'fadeInDown'] },
    styles: {
      position: 'absolute !important',
      left: '50% !important',
      top: '50% !important',
      transform: 'translate(-50%, -50%) !important',
      color: 'rgb(0, 0, 0) !important',
      borderRadius: '200px !important',
      height: '400px !important',
      width: '400px !important',
      backgroundColor: 'rgb(255, 255, 255) !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '4px',
      borderStyle: 'solid',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-inner-circle': {
    slot: { textContent: '' },
    attribute: { placeholder: '' },
    styles: {
      color: 'rgb(0, 0, 0) !important',
      position: 'absolute !important',
      borderRadius: '190px !important',
      height: '380px !important',
      width: '380px !important',
      backgroundColor: 'rgb(223, 122, 94) !important',
      borderColor: 'rgb(223, 122, 94) !important',
      borderWidth: '0px',
      borderStyle: 'solid',
      left: '6.59998px !important',
      top: '6.60001px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-1': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '0px',
      borderstyle: 'solid',
      left: '119px !important',
      top: '18px !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-2': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '0px',
      borderstyle: 'solid',
      left: '227px !important',
      top: '13px !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-star-3': {
    slot: { textContent: '&star;' },
    attribute: { placeholder: '' },
    styles: {
      color: '#c85842 !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '0px',
      borderstyle: 'solid',
      left: '174px !important',
      top: '0 !important',
      textAlign: 'center !important',
      fontSize: '35px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-text-1': {
    slot: { textContent: 'Get a Discount for shopping <br />with us' },
    attribute: { placeholder: '' },
    styles: {
      color: '#ffffff !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '0px',
      borderstyle: 'solid',
      left: '54.0999px !important',
      top: '80.8px !important',
      textAlign: 'center !important',
      fontSize: '23px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-text-2': {
    slot: { textContent: 'Get a Discount for shopping with us' },
    attribute: { placeholder: '' },
    styles: {
      color: '#ffffff !important',
      position: 'absolute !important',
      textAlgn: 'center !important',
      backgroundColor: 'transparent !important',
      borderColor: 'rgb(223, 122, 94)',
      borderWidth: '0px',
      borderstyle: 'solid',
      left: '73.7031px',
      top: '290.003px',
      textAlign: 'center !important',
      fontSize: '15px !important',
      direction: 'ltr !important',
      boxSizing: 'border-box !important',
    },
  },
  'popup-input-1': {
    slot: { textContent: '' },
    attribute: { placeholder: 'Enter Your Text Here' },
    styles: {
      position: 'absolute !important',
      left: '77.0147px !important',
      top: '167.846px !important',
      borderRadius: '2px !important',
      height: '50.5px !important',
      width: '250px !important',
      lineHeight: '1.5 !important',
      fontSize: '18px !important',
      fontFamily: 'Poppins !important',
      background: 'white !important',
      paddingRight: '10px !important',
      paddingLeft: '10px !important',
      direction: 'rtl !important',
      borderStyle: 'none',
      boxSizing: 'border-box !important',
    },
  },
  'popup-button': {
    slot: { textContent: 'Lets Go ljsoiuoisg' },
    attribute: { placeholder: '' },
    styles: {
      position: 'absolute !important',
      left: '47.01px',
      top: '231.509px',
      borderRadius: '2px !important',
      lineHeight: '1.5 !important',
      fontSize: '18px !important',
      color: '#ffffff !important',
      fontFamily: 'Poppins !important',
      background: '#000000 !important',
      paddingRight: '10px !important',
      paddingLeft: '10px !important',
      direction: 'ltr !important',
      width: '300px !important',
      height: '50.5px !important',
      backgroundColor: '#000000 !important',
      borderStyle: 'none',
      boxSizing: 'border-box !important',
    },
  },
};

export const editables = {
  text: ['textContent', 'color', 'fontSize'],
  outerCirlce: ['backgroundColor', 'borderColor', 'animationClass'],
  circle: ['backgroundColor', 'borderColor'],
  input: ['placeholder', 'direction'],
  button: ['backgroundColor', 'textContent', 'color'],
};

export default defaultPopupTemplateStyles as Record<string, Record<string, unknown>>;
